---
defaults: &defaults
  output:
    output_dir: /var/spool/apel/outgoing/00000000 # Directory for outgoing messages
    output_type: apel-0.4 # Format of outgoing messages. Choices are: apel-0.2, apel-0.4, pbs-0.1, logstash-0.1
    num_of_vms_per_file: ${ONEACCT_NUM_OF_VMS_PER_FILE} # Maximum number of virtual machine records per one output file
    apel: # Options for apel output format
      site_name: ${ONEACCT_SITE_NAME} # Usually a short provider name, e.g. CESNET
      cloud_type: ${ONEACCT_CLOUD_TYPE} # CMF type, only OpenNebula is supported
      endpoint: ${ONEACCT_ENDPOINT} # URL of your OCCI endpoint, e.g. https://fqdn.example.com:11443/
      # cloud_compute_service: # Name identifying cloud resource within the site. Allows multiple cloud resources within a site. i.e. a level of granularity.
    pbs: # Options for pbs output format
      realm: REALM # Owner's realm, e.g. META
      queue: cloud # Queue name
      scratch_type: local # Data store type
      host_identifier: on_localhost # Identifier for host OpenNebula is running on
    logstash: # Options for logstash output format
      host: localhost # Host OpenNebula is running on
      port: 11443 # Port OpenNebula's RPC is listening on
  logging:
    log_type: file # Two options: file, syslog. Defaults to stdout
    log_file: /var/log/oneacct-export/oneacct-export.log # Used when type file selected
  xml_rpc:
    secret: ${ONEACCT_XML_RPC_SECRET} # If not specified looking for secret in ONE_AUTH and ~/.one/one_auth
    endpoint: ${ONEACCT_XML_RPC_ENDPOINT} # Defaults to content of ONE_XMLRPC or content of ~/.one/one_endpoint or http://localhost:2633/RPC2
  redis:
    namespace: ${ONEACCT_REDIS_NAMESPACE} # Namespace used by redis for sidekiq jobs
    url: ${ONEACCT_REDIS_URL} # URL of redis server, defaults to redis://localhost:6379
    password: ${ONEACCT_REDIS_PASSWORD} # Password to access redis server if needed
  sidekiq:
    queue: ${ONEACCT_SIDEKIQ_QUEUE} # Name of the redis queue used by sidekiq, must match sidekiq.yml configuration

###############################################
#######  DO NOT EDIT AFTER THIS POINT  ########
###############################################

production:
  <<: *defaults


development:
  <<: *defaults


test:
  output:
    output_dir: <placeholder>
    output_type: <placeholder>
    num_of_vms_per_file: <placeholder>
    apel:
      site_name: <placeholder>
      cloud_type: <placeholder>
      endpoint: <placeholder>
    pbs:
      realm: <placeholder>
      queue: <placeholder>
      scratch_type: <placeholder>
      host_identifier: <placeholder>
    logstash:
      host: <placeholder>
      port: <placeholder>
  logging:
    log_type: <placeholder>
    log_file: <placeholder>
  xml_rpc:
    secret: <placeholder>
    endpoint: <placeholder>
  redis:
    namespace: <placeholder>
    url: http://some.random.url.com
    password: password
  sidekiq:
    queue: oneacct_export
